#!/bin/bash
# Create a private repo on github
clear
TOKEN=`cat ./token`
printf "\nTOKEN=[$token]"

# ---
echo "# repo:github " >> README.md
chmod og-rwx README.md git-config
git init
git add README.md git-config
git commit -m "initial commit"
#curl https://api.github.com/user/repos?access_token=$TOKEN -d '{"name":"github", "private":"true"}'
curl https://api.github.com/user/repos?access_token=$TOKEN -d '{"name":"github"}'
git remote add origin git@github.com:CalebCodesIT/github.git
git push -u origin master
