#!/bin/bash
# Create a private repo on github
clear

# --
USER=CalebCodesIT
TOKEN=`cat ./token`

#win
HOME=/g/dev/calebcodesit
KEY=$HOME/.ssh/id_rsa

#lin
#HOME=/g/dev/calebcodesit
#KEY=$HOME/.ssh/id_rsa

#printf "\nTOKEN=[$token]"

#-- List of repos to create
#REPOS=`cat ./repos-to-create.txt`
#REPOS="twilio sendgrid"
REPOS="aws-ec2 aws-lambda aws-lightsail aws-s3"

git config --global user.email "CalebCodesIT@gmail.com"
git config --global user.name "Caleb Codes"
for repo in $REPOS; do
	printf "\n---\nProcessing: $repo\n"
	mkdir ../$repo
	pushd .
	cd ../$repo
	pwd
	echo "# repo:$repo" >> README.md
	chmod og-rwx README.md
	git init
	git add README.md
	git commit -m "initial commit"
	#curl https://api.github.com/user/repos?access_token=$TOKEN -d '{"name":"'$repo'", "private":"true"}'
	curl https://api.github.com/user/repos?access_token=$TOKEN -d '{"name":"'$repo'"}'
	ssh-agent bash -c 'ssh-add '$KEY'; git remote add origin git@github.com:'$USER'/'$repo'.git'
	ssh-agent bash -c 'ssh-add '$KEY'; git push -u origin master'
	popd
done
