#!/bin/bash
# git clone a repo, using a specific ssh key, possibly in another directory

# ---
USER=CalebCodesIT
REPO_DIR=$HOME/repos

# win
#KEY=/g/dev/calebcodesit/.ssh/id_ed25519_no_pass_github
#REPO_DIR=/g/dev/calebcodesit/repos

# lin
KEY=$HOME/.ssh/id_ed25519_no_pass_github

# ---
clear

#REPOS=github
#REPOS="twilio sendgrid"
REPOS="aws-ec2 aws-lambda aws-lightsail aws-s3"

pushd .
for repo in $REPOS; do
	cd $REPO_DIR
	PWD=`pwd`
	printf "\n---PWD=[$pwd]---\n"
	ssh-agent bash -c 'ssh-add '$KEY'; git clone git@github.com:'$USER'/'$repo'.git'
done
popd

#id_ed25519_no_pass_github
#id_ed25519_no_pass_github.pub
# add clone all branches
