#!/bin/bash
# git clone a repo, using a specific ssh key, possibly in another directory

# ---
#KEY=$HOME/.ssh/id_ed25519_no_pass_github
#REPO_DIR=$HOME/repos

KEY=/g/dev/calebcodesit/.ssh/id_ed25519_no_pass_github
REPO_DIR=/g/dev/calebcodesit/repos
USER=CalebCodesIT

# ---
clear
pushd .
cd $REPO_DIR

#REPOS=github
REPOS="twilio sendgrid"
for repo in $REPOS; do
	ssh-agent bash -c 'ssh-add '$KEY'; git clone git@github.com:'$USER'/'$REPO'.git'
	popd
done

#id_ed25519_no_pass_github
#id_ed25519_no_pass_github.pub

# add clone all branches
