#!/bin/bash
# git clone a repo, using a specific ssh key, possibly in another directory

# ---
USER=CalebCodesIT
KEY=$HOME/.ssh/id_ed25519_no_pass_github
REPOS=$HOME/repos
REPO=github

# ---
clear
pushd .
cd $REPOS/$REPO
ssh-agent bash -c 'ssh-add '$KEY'; git pull origin master'

popd
